const PRODUCTS = [
  {id:1,name:'Lavendel',category:'Pflanzen',price:8.9,tax:13,unit:'Topf',stock:18,min:5,icon:'🪻'},
  {id:2,name:'Rosmarin',category:'Kräuter',price:4.5,tax:13,unit:'Topf',stock:23,min:6,icon:'🌿'},
  {id:3,name:'Bio-Tomaten',category:'Gemüse',price:5.9,tax:10,unit:'kg',stock:8,min:5,icon:'🍅'},
  {id:4,name:'Hortensie',category:'Pflanzen',price:18.5,tax:13,unit:'Topf',stock:4,min:5,icon:'🌸'},
  {id:5,name:'Blumenerde Bio',category:'Zubehör',price:7.9,tax:20,unit:'20 l',stock:14,min:4,icon:'🪴'},
  {id:6,name:'Gartenschere',category:'Zubehör',price:24.9,tax:20,unit:'Stück',stock:7,min:3,icon:'✂️'},
  {id:7,name:'Basilikum',category:'Kräuter',price:3.9,tax:13,unit:'Topf',stock:21,min:6,icon:'🌱'},
  {id:8,name:'Wildblumenstrauß',category:'Schnittblumen',price:16.9,tax:13,unit:'Bund',stock:6,min:4,icon:'💐'},
  {id:9,name:'Pflanzkübel Terra',category:'Zubehör',price:32,tax:20,unit:'Stück',stock:3,min:3,icon:'🏺'}
];
const INITIAL_SALES=[{id:'GW-1042',time:'09:14',method:'Karte',items:3,total:32.7,status:'Gebucht'},{id:'GW-1041',time:'08:47',method:'Bar',items:2,total:19.4,status:'Gebucht'},{id:'GW-1040',time:'08:21',method:'Bar',items:4,total:41.2,status:'Gebucht'}];
const currency=new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'});
let products=JSON.parse(localStorage.getItem('gw-products'))||structuredClone(PRODUCTS);
let sales=JSON.parse(localStorage.getItem('gw-sales'))||INITIAL_SALES;
let cart=[];let category='Alle';let paymentMethod='Bar';
const $=selector=>document.querySelector(selector);

function save(){localStorage.setItem('gw-products',JSON.stringify(products));localStorage.setItem('gw-sales',JSON.stringify(sales));}
function renderProducts(){
  const query=$('#searchInput').value.toLowerCase();
  const list=products.filter(p=>(category==='Alle'||p.category===category)&&p.name.toLowerCase().includes(query));
  $('#productGrid').innerHTML=list.map(p=>`<button class="product" data-id="${p.id}" ${p.stock<1?'disabled':''}><span class="product-visual">${p.icon}</span><span class="product-info"><span class="product-name">${p.name}</span><span class="product-meta">${p.category} · ${p.unit}</span><span class="product-bottom"><span class="product-price">${currency.format(p.price)}</span><span class="stock ${p.stock<=p.min?'low':''}">${p.stock} verfügbar</span></span></span></button>`).join('')||'<p class="empty">Keine Produkte gefunden.</p>';
  document.querySelectorAll('.product').forEach(button=>button.onclick=()=>addToCart(+button.dataset.id));
}
function renderFilters(){const cats=['Alle',...new Set(products.map(p=>p.category))];$('#filters').innerHTML=cats.map(c=>`<button class="filter ${c===category?'active':''}" data-category="${c}">${c}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderFilters();renderProducts()})}
function addToCart(id){const product=products.find(p=>p.id===id),line=cart.find(i=>i.id===id),quantity=line?.quantity||0;if(quantity>=product.stock)return showToast('Nicht mehr Bestand verfügbar.');if(line)line.quantity++;else cart.push({...product,quantity:1});renderCart()}
function changeQuantity(id,amount){const line=cart.find(i=>i.id===id);if(!line)return;if(amount>0&&line.quantity>=products.find(p=>p.id===id).stock)return showToast('Nicht mehr Bestand verfügbar.');line.quantity+=amount;if(line.quantity<=0)cart=cart.filter(i=>i.id!==id);renderCart()}
function totals(){const subtotal=cart.reduce((sum,i)=>sum+i.price*i.quantity,0);const tax=cart.reduce((sum,i)=>sum+(i.price*i.quantity)-(i.price*i.quantity/(1+i.tax/100)),0);return{subtotal,tax}}
function renderCart(){const count=cart.reduce((s,i)=>s+i.quantity,0),{subtotal,tax}=totals();$('#cartCount').textContent=count;$('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><div><strong>${i.name}</strong><div class="quantity"><button data-id="${i.id}" data-delta="-1">−</button><small>${i.quantity} × ${currency.format(i.price)}</small><button data-id="${i.id}" data-delta="1">＋</button></div></div><span>${currency.format(i.price*i.quantity)}</span></div>`).join(''):'<div class="empty"><span>🧺</span>Der Warenkorb ist noch leer.<br>Tippe auf ein Produkt.</div>';document.querySelectorAll('.quantity button').forEach(b=>b.onclick=()=>changeQuantity(+b.dataset.id,+b.dataset.delta));$('#subtotal').textContent=currency.format(subtotal);$('#tax').textContent=currency.format(tax);$('#total').textContent=$('#checkoutTotal').textContent=currency.format(subtotal);$('#checkout').disabled=!cart.length;}
function renderDashboard(){const booked=sales.filter(s=>s.status==='Gebucht'),revenue=booked.reduce((s,i)=>s+i.total,0),cash=booked.filter(s=>s.method==='Bar').reduce((s,i)=>s+i.total,200);$('#revenue').textContent=currency.format(revenue);$('#cashBalance').textContent=currency.format(cash);$('#transactionCount').textContent=booked.length;$('#averageSale').textContent=currency.format(booked.length?revenue/booked.length:0)}
function renderJournal(){$('#journalBody').innerHTML=sales.map(s=>`<tr><td><strong>${s.id}</strong></td><td>${s.time}</td><td>${s.method}</td><td>${s.items}</td><td><strong>${currency.format(s.total)}</strong></td><td><span class="badge ${s.status==='Storniert'?'void':''}">${s.status}</span></td><td>${s.status==='Gebucht'?`<button class="row-action" data-void="${s.id}">Stornieren</button>`:''}</td></tr>`).join('');document.querySelectorAll('[data-void]').forEach(b=>b.onclick=()=>{if(confirm(`Beleg ${b.dataset.void} wirklich stornieren?`)){sales.find(s=>s.id===b.dataset.void).status='Storniert';save();renderAll();showToast('Buchung wurde storniert.')}})}
function renderStock(){const low=products.filter(p=>p.stock<=p.min).length;$('#stockSummary').textContent=`${products.length} Artikel · ${low} nachzubestellen`;$('#stockBody').innerHTML=products.map(p=>`<tr><td><strong>${p.icon} ${p.name}</strong></td><td>${p.category}</td><td>${p.unit}</td><td>${currency.format(p.price)}</td><td>${p.stock}</td><td><span class="badge ${p.stock<=p.min?'warn':''}">${p.stock<=p.min?'Nachbestellen':'Verfügbar'}</span></td></tr>`).join('')}
function renderAll(){renderFilters();renderProducts();renderCart();renderDashboard();renderJournal();renderStock()}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function openPayment(){const total=totals().subtotal;$('#paymentAmount').textContent=currency.format(total);$('#cashGiven').value='';$('#changeAmount').textContent=currency.format(0);$('#paymentDialog').showModal()}
function completePayment(){const total=totals().subtotal;if(paymentMethod==='Bar'){const given=parseFloat($('#cashGiven').value.replace(',','.'));if(!given||given<total)return showToast('Der gegebene Betrag ist zu niedrig.')}cart.forEach(line=>products.find(p=>p.id===line.id).stock-=line.quantity);const next=1040+sales.length+1;sales.unshift({id:`GW-${next}`,time:new Date().toLocaleTimeString('de-AT',{hour:'2-digit',minute:'2-digit'}),method:paymentMethod,items:cart.reduce((s,i)=>s+i.quantity,0),total,status:'Gebucht'});cart=[];save();renderAll();$('#paymentDialog').close();showToast(`Zahlung gebucht · Beleg GW-${next}`)}
function switchView(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$('#viewTitle').textContent={kassa:'Guten Morgen, Lisa.',journal:'Kassenjournal',bestand:'Lagerbestand'}[name]}
function exportCsv(){const rows=[['Beleg','Zeit','Zahlungsart','Artikel','Summe','Status'],...sales.map(s=>[s.id,s.time,s.method,s.items,s.total.toFixed(2),s.status])];const blob=new Blob([rows.map(r=>r.join(';')).join('\n')],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='gruenwerk-kassenjournal.csv';link.click();URL.revokeObjectURL(link.href);showToast('Kassenjournal exportiert.')}

$('#todayLabel').textContent=new Intl.DateTimeFormat('de-AT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date()).toUpperCase();
$('#searchInput').oninput=renderProducts;$('#clearCart').onclick=()=>{cart=[];renderCart()};$('#checkout').onclick=openPayment;$('#newSale').onclick=()=>{switchView('kassa');cart=[];renderCart();$('#searchInput').focus()};$('#confirmPayment').onclick=completePayment;$('#cashGiven').oninput=e=>$('#changeAmount').textContent=currency.format(Math.max(0,(parseFloat(e.target.value.replace(',','.'))||0)-totals().subtotal));document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{paymentMethod=b.dataset.method;document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('selected',x===b));$('#cashInputWrap').hidden=paymentMethod!=='Bar'});document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#exportCsv').onclick=exportCsv;$('#closeCash').onclick=()=>{exportCsv();showToast('Kassenabschluss wurde erstellt.')};$('#resetDemo').onclick=()=>{if(confirm('Demo-Daten wirklich zurücksetzen?')){localStorage.clear();products=structuredClone(PRODUCTS);sales=structuredClone(INITIAL_SALES);cart=[];renderAll();showToast('Demo wurde zurückgesetzt.')}};
renderAll();
